version: '3.7'
services:
    nginx:
      image: nginx:stable-alpine
      container_name: cmp-nginx-container
      ports:
        - "80:80"
      volumes:
        - ./app-backend:/var/www/html/cmp/api 
        - ./app-frontend:/var/www/html/cmp/frontend 
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on: 
        - php
        - mysql
      networks:
        - cmp-network

    react:
      image: cmp-react-image
      container_name: cmp-react-container
      build:          # let docker know that we build with dockerfile in locally instead of dockerhub
        context: ./app-frontend   # which is the directory dockerfile will be searched for
        dockerfile: Dockerfile    # the file name that will be build
      ports:
        - "3000:3000"
      networks:
        - cmp-network


    php:
      image: cmp-php-image
      container_name: cmp-php-container
      build:
        context: ./app-backend/
        dockerfile: Dockerfile
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      working_dir: /var/www/html
      volumes:
        - ./app-backend:/var/www/html/cmp/api
        - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      ports:
        - "9000:9000"
      networks:
        - cmp-network
      depends_on:
        - mysql

    mysql:
      image: mysql:5.7.22
      container_name: cmp-mysql-container
      restart: unless-stopped
      tty: true
      environment:
        # MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d:ro
        - cmp_db_data:/var/lib/mysql:rw
        # - ./mysql/backup:/var/lib/mysql:rw
      ports:
        - "4306:3306"
      networks:
        - cmp-network

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: cmp-db-phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: mysql  # Host of the mysql container run on / localhost ip
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - mysql
      ports:
        - "8443:80"
      networks:
        - cmp-network

networks:
  cmp-network:
    driver: bridge


volumes:
  cmp_db_data:
    # driver: "local"