version: '3.7'
services:

    frontend:
      container_name: cmp-frontend
      build:
        context: ./app-frontend 
      ports:
        - "3000:3000"
      networks:
        - cmp-frontend-network

    backend:
      container_name: cmp-backend
      build:
        context: ./app-backend/
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      working_dir: /var/www
      volumes:
        - ./app-backend:/var/www
      ports:
        - "8001:8001"
      networks:
        - cmp-frontend-network
        - cmp-db-network

    appdb:
      image: mysql:5.7
      container_name: cmp-db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
      networks:
        - cmp-db-network

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: cmp-db-phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: appdb
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - appdb
      ports:
        - 8443:80
      networks:
        - cmp-db-network

networks:
  cmp-frontend-network:
    driver: bridge
  cmp-db-network: